### ISSUE TITLE
UnityBridge does not compile on Unity 6000.5 (120x CS0619 from the instance-ID APIs)

### ISSUE THREAD

**Issue by quintenu** [bigdra50/unity-cli#121]
## Summary

`com.bigdra50.unity-bridge` v3.12.0 fails to build on Unity 6000.5 (Unity 6.5). Unity promoted
`Object.GetInstanceID()`, `Selection.activeInstanceID` and `EditorUtility.InstanceIDToObject(int)`
from *warning*-obsolete (CS0618) to **error**-obsolete (CS0619), so `UnityBridge.Editor.asmdef`
produces 120 errors and no assembly.

Because the assembly never builds, `[InitializeOnLoad]` never runs — so **`Window > Unity Bridge`
does not exist in the menu at all**, and there is no way to start or connect the bridge. From the
CLI side this surfaces only as `CONNECTION_FAILED` / `INSTANCE_NOT_FOUND`, which is misleading: it
looks like a relay or networking problem rather than a compile failure. Worth considering a clearer
failure mode, since the real cause is only visible in `Editor.log`.

## Environment

| | |
|---|---|
| Unity | 6000.5.8f1 (URP 17.5.0) |
| UnityBridge | v3.12.0 (commit 68692892, current HEAD) |
| unity-cli | 3.12.0 (`uv tool install`) |
| OS | Windows 11 |

## Repro

1. Unity 6000.5.8f1 project.
2. Add `https://github.com/bigdra50/unity-cli.git?path=UnityBridge#v3.12.0`.
3. Let the Editor compile.

Result: `*** Tundra build failed`, 120 × CS0619, no `UnityBridge.Editor.dll`, no Unity Bridge menu.

```
Editor\Tools\GameObject.cs(190,24): error CS0619: 'Object.GetInstanceID()' is obsolete:
'Use GetEntityId instead.'
Editor\Tools\EditorSelection.cs(46,40): error CS0619: 'Selection.activeInstanceID' is obsolete:
'Use activeEntityId instead.'
Editor\Helpers\GameObjectFinder.cs(23,27): error CS0619: 'EditorUtility.InstanceIDToObject(int)'
is obsolete: 'Use EditorUtility.EntityIdToObject instead.'
```

## Affected call sites (20)

| File | Sites |
|---|---|
| `Editor/Tools/Component.cs` | 10 |
| `Editor/Tools/EditorSelection.cs` | 3 |
| `Editor/Tools/GameObject.cs` | 3 |
| `Editor/Tools/Asset.cs` | 1 |
| `Editor/Tools/Scene.cs` | 1 |
| `Editor/Helpers/ApiSafetyGuard.cs` | 1 |
| `Editor/Helpers/GameObjectFinder.cs` | 1 |

## The part that makes this non-trivial

A straight rename to `GetEntityId()` is **not** sufficient, for two reasons.

**1. `EntityId` → `int` is also error-obsolete.** The obvious `(int)obj.GetEntityId()` does not
compile either:

```
error CS0619: 'EntityId.implicit operator int(EntityId)' is obsolete:
'EntityId will not be representable by an int in the future.
 This casting operator will be removed in a future version.'
```

`EntityId`'s non-obsolete surface is `ToULong` / `FromULong` / `GetRawData` / `IsValid` — no
non-obsolete int accessor.

**2. The wire protocol is int-based.** These values are written straight into `JObject` as
`["instanceID"]` / `["gameObjectId"]`, and the CLI parses them as JSON integers. Letting an
`EntityId` struct reach the serializer would emit a nested object and silently break every client.
Scene objects also get *negative* ids, so a naive `ToULong` returns ~1.8e19 instead of e.g. `-1706`
and all lookups miss.

Note the reverse direction (`int` → `EntityId`) is only **CS0618**, so a `#pragma` still works there.

## Suggested fix

A single compat helper, with all 20 sites routed through it. Obsolete-ness is a compile-time
diagnostic only, so invoking the operator via a cached delegate is legal and preserves the exact
legacy value, negatives included:

```csharp
private static readonly Func<EntityId, int> ToIntFunc = BuildToInt();

private static Func<EntityId, int> BuildToInt()
{
    var op = typeof(EntityId)
        .GetMethods(BindingFlags.Public | BindingFlags.Static)
        .FirstOrDefault(m =>
            m.Name == "op_Implicit" &&
            m.ReturnType == typeof(int) &&
            m.GetParameters().Length == 1 &&
            m.GetParameters()[0].ParameterType == typeof(EntityId));

    if (op != null)
        return (Func<EntityId, int>)Delegate.CreateDelegate(typeof(Func<EntityId, int>), op);

    return id => unchecked((int)EntityId.ToULong(id));   // low 32 bits keep the legacy signed int
}
```

For a version-spanning fix, gating on `UNITY_6000_5_OR_NEWER` would keep the 2022.3 floor intact.

Longer term the deprecation message is a warning shot: when ids widen past 32 bits, the CLI's
integer protocol will need to widen with them.

## Also (minor, warning only)

`Editor/Tools/UITree.cs:591` — `FindObjectsSortMode` and the overloads taking it are CS0618 on
6000.5. The no-argument `FindObjectsByType<T>()` is the documented replacement and already returns
unsorted results, so behaviour is unchanged.

## Verification

Applied locally as a vendored fork against Unity 6000.5.8f1: 120 errors → 0, `UnityBridge.Editor.dll`
builds, bridge connects, and `u state` / `u scene hierarchy` / `u component list` all behave. Ids
round-trip correctly — `scene hierarchy` reports `Main Camera -1706`, and `component list
--target-id=-1706` resolves to the same components as lookup by name.

Happy to open a PR if the approach looks right.
